config/routes.rb
Rails.application.routes.draw do
  resources :searches do
    member do
      post :create
    end
    collection do
      get :index, :update
    end
  end
  resources :articles, trailing_slash: true do
    collection do
      post :search
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  scope :filter_by_query, -> (query) { where('content ILIKE ?', "%#{query}%") }
end

app/models/search.rb
class Search < ApplicationRecord
  scope :larger_queries, -> (query_value) { find_by_sql(["SELECT * FROM searches WHERE query ILIKE '%' || ? || '%'", query_value])
  }
  scope :smaller_queries, -> (query_value) { find_by_sql(["SELECT * FROM searches WHERE ? ILIKE '%' || query || '%'", query_value]) }

  scope :query_count_by_ip_address, -> () { group(:query).select('query, COUNT(DISTINCT ip_address) as user_count') }

  def self.create_and_cleanup(query_value, ip_address)
    larger_queries = Search.larger_queries(query_value)
    if larger_queries.empty?
      Search.create(query: query_value, ip_address: ip_address)
      smaller_queries = Search.smaller_queries(query_value)
      smaller_queries.each do |record|
        record.destroy if record.query.length < query_value.length
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :set_user_ip_address, only: %i[ index show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  def search
    if params.dig(:query).present?
      @articles = Article.filter_by_query(params[:query])
    else
      @articles = []
    end
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update("search_results",
                              partial: "articles/search_results",
                              locals: { articles: @articles })
        ]
      end
    end
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  def set_user_ip_address
    @ip_address = request.remote_ip
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:content)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def create
    ip_address = request.remote_ip
    Search.create_and_cleanup(params.dig(:query), ip_address)
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update("searches",
                              partial: "searches/searches_list",
                              locals: { searches: Search.all.where(ip_address: ip_address) })
        ]
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Content:</strong>
    <%= article.content %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, class: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/_search_results.html.erb
<div class="flex flex-col gap-y-5 p-5">
  <p class="font-bold "> Search Result </p>
  <div class="bg-emerald-50">
    <% @articles.each do |a| %>
      <p class="text-indigo-900"> <%= a.content %> </p>
    <% end %>
  </div>
  <hr>
</div>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<div class="border m-3 p-3 flex flex-row gap-x-5 justify-center" data-controller="search-form">
  <div class="bg-blue-50 p-3 w-6/12">
    <%= form_with url: search_articles_path,
                  method: :post,
                  class: 'my-5' do |form| %>
      <%= form.search_field :query,
                            value: params[:query],
                            'data-action': "input->search-form#search" %>
      <input type="hidden"
             name="format"
             value="turbo_stream">
    <% end %>

    <div id="search_results" class="bg-gray-50"></div>

    <p style="color: green"><%= notice %></p>
  </div>
  <div class="bg-yellow-50 w-6/12 flex flex-col items-center-center p-3">
    <h1>User searches</h1>
    <div id="searches">
      <%= render partial: "searches/searches_list",
                 locals: { searches: Search.all.where(ip_address: @ip_address) } %>
    </div>
  </div>
</div>

<div class="flex gap-x-5">
  <div class="w-6/12 bg-emerald-50 p-2">
    <h1>Articles</h1>

    <div id="articles">
      <% @articles.each do |article| %>
        <p>
          <%= link_to article.content, article %>
        </p>
      <% end %>
    </div>
  </div>
  <div class="w-6/12 bg-amber-50 p-2">
    <p> Analytics </p>
    <% result = Search.query_count_by_ip_address%>
    <% result.each do |item| %>
      <p>Query: <%= item.query %>, Count: <%= item.user_count %></p>
    <% end %>
  </div>
</div>

<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnalyticsTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/searches/_searches_list.html.erb
<div class="flex flex-col gap-y-2">
  <div class="bg-emerald-50">
    <% searches.each do |s| %>
      <p class="text-indigo-900"> <%= s.query %> </p>
    <% end %>
  </div>
</div>